In [1]:
!pip install lightgbm

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: lightgbm in c:\users\andre\appdata\roaming\python\python39\site-packages (4.6.0)
Requirement already satisfied: numpy>=1.17.0 in c:\programdata\anaconda3\lib\site-packages (from lightgbm) (1.21.5)
Requirement already satisfied: scipy in c:\programdata\anaconda3\lib\site-packages (from lightgbm) (1.9.1)

In [2]:
# Импорт библиотек
import numpy as np
import pandas as pd
import seaborn as sns

import lightgbm as lgb # импорт библиотеки LightGBM
from lightgbm import LGBMRegressor

from sklearn.model_selection import train_test_split

from sklearn.metrics import mean_squared_error
from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor

from sklearn.preprocessing import StandardScaler

#import category_encoders as ce

In [3]:
 # чтение файла с данными для построения модели
data = pd.read_csv('all_reagions_model.csv')

In [4]:
#Выводим датафрейм data на экран
data

,target0,features0,target1,features1,target2,features2,target3,features3,target4,features4,...,target81,features81,target82,features82,target83,features83,target84,features84,target85,features85
0,15219036,19787155,152657,190715,122714,155664,137302,171057,212100,269620,...,97189,121399,16519,19979,56156,63805,20337,24556,7453,8596
1,15705924,20295175,155969,195169,124759,158010,140457,174329,219012,276153,...,98593,123890,16648,20080,57508,63483,20581,24531,7510,8569
2,16137286,20887961,159569,201544,128435,160801,142556,178775,225099,285256,...,99767,126997,16653,20147,58359,63210,20948,24722,7411,8653
3,16565591,21365236,162634,207532,128975,163396,145066,182225,232259,291555,...,100640,128881,16512,20371,59422,62485,20890,24662,7346,8660
4,16893700,21911893,164881,213718,128593,165948,146128,185131,236650,297916,...,100575,130818,16265,20699,60439,62248,20989,24668,7301,8758
5,17314160,22410642,167597,218265,130443,168700,147395,187562,243233,305747,...,100347,131412,16122,20861,61346,62588,20780,24596,7266,8901
6,17745037,22773674,170158,218766,131499,169993,150421,189556,251400,311580,...,100068,131804,16170,20983,62322,65503,20796,24925,7228,8987
7,17997296,23638919,166147,218335,130690,169958,151459,189406,255927,313914,...,99401,131538,15944,21002,63014,67384,20337,24976,7157,8996
8,17988139,23128159,158684,220379,127953,170449,149210,188978,256841,317466,...,97377,130498,15732,20886,63363,67846,19799,24710,7053,9186

In [5]:
#Выводим основную информацию о датафрейме
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Columns: 172 entries, target0 to features85
dtypes: int64(172)
memory usage: 12.2 KB

In [6]:
 # чтение файла с данными для предсказания значений
features_test = pd.read_csv('all_reagions_predict.csv')
#Выводим датафрейм data на экран
features_test

,year,features0,features1,features2,features3,features4,features5,features6,features7,features8,...,features76,features77,features78,features79,features80,features81,features82,features83,features84,features85
0,2025,23154041,218934,169362,187058,318070,126224,157941,91610,157055,...,202610,181252,47634,270207,202529,129704,20693,68603,24514,9274
1,2026,22993937,215313,165836,183186,316356,123560,158527,90303,155172,...,201770,177665,47787,268016,201321,127710,20409,68448,24075,9294
2,2027,22699332,210683,161171,178462,312604,120358,158138,88660,152353,...,199710,172923,47707,265054,199626,125039,19991,67833,23435,9232
3,2028,22310665,205072,156212,172868,306922,117056,156923,86337,149459,...,196628,168580,47480,260655,196776,122414,19576,67727,22897,9181
4,2029,21813985,199203,151179,166861,300480,113654,154421,83739,145780,...,192875,163598,47139,255006,193071,119085,19085,67077,22252,9083
5,2030,21193165,191949,145213,159896,292064,109862,151378,80613,140595,...,188567,158352,46335,248092,187757,115067,18430,66284,21462,8951
6,2031,20449487,183863,138647,151999,281717,105394,147197,77009,134924,...,183422,152384,45295,239630,181213,110465,17695,65137,20590,8753
7,2032,19705616,175798,132407,144636,271552,100834,142937,73492,129411,...,178236,146687,44141,231248,174638,106020,16992,63824,19781,8550
8,2033,18943074,167758,126313,137155,260899,96496,138357,70010,123773,...,172756,140856,43021,222894,167814,101695,16324,62466,18980,8330
9,2034,18178844,159901,119524,129298,249780,92211,133082,66495,118118,...,167781,135710,41867,214455,160834,97565,15699,61024,18082,8101
10,2035,17492718,152624,113527,122034,239683,88411,128324,63250,112966,...,163874,131521,40901,206981,154953,93896,15175,59074,17306,7914
11,2036,17008297,147445,109192,116925,232353,85740,125007,60762,109522,...,161706,128694,40252,201767,150561,91223,14797,57946,16732,7791
12,2037,16616956,143126,105356,112416,226156,83749,122297,58861,106626,...,160302,126654,39863,197607,146760,89187,14535,57455,16245,7720
13,2038,16366199,140122,102721,109438,221997,82622,120940,57315,104862,...,159948,125651,39714,195123,144104,87997,14417,57050,15911,7715
14,2039,16196444,138080,100670,107431,218759,81969,119951,56172,103564,...,159797,125118,39701,193290,142381,87166,14328,57233,15645,7748
15,2040,16077876,136343,99131,105747,216252,81551,119454,55145,102705,...,160546,125058,39844,192225,140772,86754,14334,57526,15442,7793
16,2041,16066222,135960,98358,105079,215372,81448,119750,54530,102667,...,161882,124997,40184,192315,140125,86849,14387,57750,15343,7872
17,2042,16139753,136346,98061,105012,215749,81837,120811,54197,103212,...,163965,125538,40747,193559,140178,87370,14520,58368,15303,7976
18,2043,16316695,137754,98382,105693,217690,82775,122745,54235,104498,...,166884,126672,41555,196089,141081,88415,14726,59301,15343,8114
19,2044,16533661,139592,98904,106682,220327,83962,125058,54398,106090,...,170008,127931,42464,199188,142316,89664,14960,60343,15393,8247
20,2045,16776245,141747,99523,107862,223483,85339,127621,54619,107887,...,173207,129245,43426,202692,143759,91025,15210,61439,15445,8381

# Обучение моделей

In [7]:
# Зададим RandomState
RANDOMSTATE = 12345

In [8]:
# Функция для одного параметра
def split_one_region(df, features_df, target_df, test, year_test,features_test):
    # Разбиваем выборку в соотношении 78:22. 
    train, valid = np.split(df.sample(frac=1, random_state=RANDOMSTATE), [int(.78*len(df))])

    # Проверяем сколько строк и столбцов в полученных датасетах
    print('Размер обучающей выборки - {:.0%}'.format(train.shape[0] / data.shape[0]))
    print('Размер валидационной выборки- {:.0%}'.format(valid.shape[0] / data.shape[0]))
    
    print('Проверяем размер обучающей выборки')
    print(train.shape) 
    print('Проверяем размер валидационной выборки')
    print(valid.shape)
    
    # Разбиваем на целевой признак и признаки модели.
    target_train = train[target_df]
    features_train = train[features_df]

    target_valid = valid[target_df]
    features_valid = valid[features_df]
    
    model = LinearRegression()
    model.fit(features_train, target_train)

    predicted_target= model.predict(features_valid) #предсказание на валидационной выборке
    mean_predicted_target = predicted_target.mean()
    

    print('')
    print('Среднее значение предсказанного количества школьников за год :', predicted_target.mean())
    print('RMSE :', mean_squared_error(target_valid, predicted_target)**0.5)
    
    print('')
    # print('Годы: ')
    year = test[year_test]
    #  print(year)
    
    
    features_test = test[features_test]
    predicted_target= model.predict(features_test) #предсказание на валидационной выборке
    #predicted_target = np.insert(predicted_target,0, features_test)
    #predicted_target = predicted_target.insert(0, features_test)
    predicted_target = pd.Series(list(map(int, predicted_target)))
    predicted_target = pd.DataFrame(predicted_target, columns= [target_df])
    print('')
    print('Предсказания на 2025-2045 годы: ')
    print('')
    #print(predicted_target)
    predicted_all = year.join(predicted_target)
    print(predicted_all)
    predicted_all.to_csv('output0csv')

In [9]:
split_one_region(data, ['features14'],'target14', features_test,['year'], ['features14'])

Размер обучающей выборки - 78%
Размер валидационной выборки- 22%
Проверяем размер обучающей выборки
(7, 172)
Проверяем размер валидационной выборки
(2, 172)

Среднее значение предсказанного количества школьников за год : 96567.11108832463
RMSE : 1139.232869452029


Предсказания на 2025-2045 годы:

    year  target14
0   2025     90675
1   2026     83002
2   2027     74040
3   2028     65537
4   2029     54845
5   2030     43903
6   2031     31335
7   2032     18641
8   2033      5894
9   2034     -6774
10  2035    -17820
11  2036    -26093
12  2037    -32218
13  2038    -36347
14  2039    -38928
15  2040    -40974
16  2041    -42331
17  2042    -42047
18  2043    -40154
19  2044    -37517
20  2045    -34314

In [10]:
# Функция для всех регионов
def split(df, test, year_test):
    predicted_all = test[year_test]
    year = test[year_test]
    #print(year)
    
    # Разбиваем выборку в соотношении 78:22. 
    train, valid = np.split(df.sample(frac=1, random_state=RANDOMSTATE), [int(.78*len(df))])

    # Проверяем сколько строк и столбцов в полученных датасетах
    print('Размер обучающей выборки - {:.0%}'.format(train.shape[0] / data.shape[0]))
    print('Размер валидационной выборки- {:.0%}'.format(valid.shape[0] / data.shape[0]))
    
    print('Проверяем размер обучающей выборки')
    print(train.shape) 
    print('Проверяем размер валидационной выборки')
    print(valid.shape)
    
    for i in range(86):
        target_df = 'target' + str(i)
        features_df = []
        features_df.append('features' + str(i))

        # Разбиваем на целевой признак и признаки модели.
        target_train = train[target_df]
        features_train = train[features_df]

        target_valid = valid[target_df]
        features_valid = valid[features_df]
    
        model = LinearRegression()
        model.fit(features_train, target_train)

        predicted_target= model.predict(features_valid) #предсказание на валидационной выборке
        mean_predicted_target = predicted_target.mean()
    
        print(i)
        print('Среднее значение предсказанного количества школьников за год :', int(predicted_target.mean()))
        print('RMSE :', mean_squared_error(target_valid, predicted_target)**0.5)
   
    
        features_test = test[features_df]
        predicted_target= model.predict(features_test) #предсказание на валидационной выборке

        predicted_target = pd.Series(list(map(int, predicted_target)))
        predicted_target = pd.DataFrame(predicted_target, columns= [target_df])
        #print(predicted_target)
        predicted_all = predicted_all.join(predicted_target)
    print(predicted_all)
    predicted_all.to_csv('output.csv')

In [11]:
split(data, features_test,['year'])

Размер обучающей выборки - 78%
Размер валидационной выборки- 22%
Проверяем размер обучающей выборки
(7, 172)
Проверяем размер валидационной выборки
(2, 172)
0
Среднее значение предсказанного количества школьников за год : 16725728
RMSE : 7152.666966111123
1
Среднее значение предсказанного количества школьников за год : 161862
RMSE : 1834.1917263927276
2
Среднее значение предсказанного количества школьников за год : 127872
RMSE : 1772.754763959164
3
Среднее значение предсказанного количества школьников за год : 145867
RMSE : 1078.574581927374
4
Среднее значение предсказанного количества школьников за год : 236430
RMSE : 2351.2751020610044
5
Среднее значение предсказанного количества школьников за год : 101939
RMSE : 554.4218365280615
6
Среднее значение предсказанного количества школьников за год : 112719
RMSE : 791.6976087272567
7
Среднее значение предсказанного количества школьников за год : 72744
RMSE : 162.14737901612023
8
Среднее значение предсказанного количества школьников за год : 116499
RMSE : 548.9206472906274
9
Среднее значение предсказанного количества школьников за год : 123442
RMSE : 497.46700082446733
10
Среднее значение предсказанного количества школьников за год : 927029
RMSE : 3114.8494768991177
11
Среднее значение предсказанного количества школьников за год : 76722
RMSE : 474.54761817482836
12
Среднее значение предсказанного количества школьников за год : 112360
RMSE : 1236.193056734198
13
Среднее значение предсказанного количества школьников за год : 93278
RMSE : 523.2385715318228
14
Среднее значение предсказанного количества школьников за год : 96567
RMSE : 1139.232869452029
15
Среднее значение предсказанного количества школьников за год : 137821
RMSE : 378.20505232710735
16
Среднее значение предсказанного количества школьников за год : 142013
RMSE : 1054.6813802474123
17
Среднее значение предсказанного количества школьников за год : 137158
RMSE : 970.3521252643952
18
Среднее значение предсказанного количества школьников за год : 1080581
RMSE : 18430.804853585687
19
Среднее значение предсказанного количества школьников за год : 70390
RMSE : 549.1305679262094
20
Среднее значение предсказанного количества школьников за год : 101521
RMSE : 718.2628450808244
21
Среднее значение предсказанного количества школьников за год : 127020
RMSE : 998.4193352287376
22
Среднее значение предсказанного количества школьников за год : 6393
RMSE : 49.549307158208265
23
Среднее значение предсказанного количества школьников за год : 138684
RMSE : 821.5435300018125
24
Среднее значение предсказанного количества школьников за год : 116322
RMSE : 1193.2468964858156
25
Среднее значение предсказанного количества школьников за год : 172629
RMSE : 4342.359308940888
26
Среднее значение предсказанного количества школьников за год : 81458
RMSE : 505.26097519875105
27
Среднее значение предсказанного количества школьников за год : 65439
RMSE : 403.48320352734027
28
Среднее значение предсказанного количества школьников за год : 67369
RMSE : 286.9177117520577
29
Среднее значение предсказанного количества школьников за год : 539015
RMSE : 14073.944062706076
30
Среднее значение предсказанного количества школьников за год : 55279
RMSE : 512.3727894987975
31
Среднее значение предсказанного количества школьников за год : 33916
RMSE : 520.5958061242396
32
Среднее значение предсказанного количества школьников за год : 215838
RMSE : 1127.8941980341328
33
Среднее значение предсказанного количества школьников за год : 706424
RMSE : 3322.295832730144
34
Среднее значение предсказанного количества школьников за год : 121081
RMSE : 1138.0669009360972
35
Среднее значение предсказанного количества школьников за год : 256650
RMSE : 1688.0851686793806
36
Среднее значение предсказанного количества школьников за год : 441174
RMSE : 4866.934315942758
37
Среднее значение предсказанного количества школьников за год : 48232
RMSE : 548.4296417383933
38
Среднее значение предсказанного количества школьников за год : 434851
RMSE : 8979.881199516794
39
Среднее значение предсказанного количества школьников за год : 81477
RMSE : 4573.890708484722
40
Среднее значение предсказанного количества школьников за год : 110614
RMSE : 459.0157628382427
41
Среднее значение предсказанного количества школьников за год : 54948
RMSE : 617.9659973969328
42
Среднее значение предсказанного количества школьников за год : 92826
RMSE : 4059.6029216481716
43
Среднее значение предсказанного количества школьников за год : 295684
RMSE : 1468.4651451298662
44
Среднее значение предсказанного количества школьников за год : 304583
RMSE : 3129.6733698931257
45
Среднее значение предсказанного количества школьников за год : 495081
RMSE : 2019.8825045642461
46
Среднее значение предсказанного количества школьников за год : 80357
RMSE : 554.532118933514
47
Среднее значение предсказанного количества школьников за год : 73314
RMSE : 301.7667204638941
48
Среднее значение предсказанного количества школьников за год : 447162
RMSE : 2873.4029139787526
49
Среднее значение предсказанного количества школьников за год : 189544
RMSE : 858.1231893187638
50
Среднее значение предсказанного количества школьников за год : 142479
RMSE : 511.84823693606955
51
Среднее значение предсказанного количества школьников за год : 323381
RMSE : 2101.6551272075153
52
Среднее значение предсказанного количества школьников за год : 140401
RMSE : 804.2788746902776
53
Среднее значение предсказанного количества школьников за год : 336658
RMSE : 2159.0417543912286
54
Среднее значение предсказанного количества школьников за год : 238203
RMSE : 845.3801851540355
55
Среднее значение предсказанного количества школьников за год : 129501
RMSE : 1667.8735602408676
56
Среднее значение предсказанного количества школьников за год : 342053
RMSE : 2721.0591792397845
57
Среднее значение предсказанного количества школьников за год : 247257
RMSE : 1109.608704535151
58
Среднее значение предсказанного количества школьников за год : 123252
RMSE : 647.6133893466447
59
Среднее значение предсказанного количества школьников за год : 100294
RMSE : 550.4227428174095
60
Среднее значение предсказанного количества школьников за год : 523018
RMSE : 3833.8989497667903
61
Среднее значение предсказанного количества школьников за год : 217627
RMSE : 1454.0532483196205
62
Среднее значение предсказанного количества школьников за год : 223845
RMSE : 821.0428790624285
63
Среднее значение предсказанного количества школьников за год : 76583
RMSE : 502.6889195074964
64
Среднее значение предсказанного количества школьников за год : 412052
RMSE : 2825.1129363350815
65
Среднее значение предсказанного количества школьников за год : 38142
RMSE : 215.822855970565
66
Среднее значение предсказанного количества школьников за год : 68788
RMSE : 674.8358074270835
67
Среднее значение предсказанного количества школьников за год : 71910
RMSE : 356.59219080496905
68
Среднее значение предсказанного количества школьников за год : 276199
RMSE : 1526.5348496576046
69
Среднее значение предсказанного количества школьников за год : 349880
RMSE : 1825.357530523856
70
Среднее значение предсказанного количества школьников за год : 330164
RMSE : 1133.9341951046094
71
Среднее значение предсказанного количества школьников за год : 315440
RMSE : 1749.255488246589
72
Среднее значение предсказанного количества школьников за год : 341372
RMSE : 2265.27866738711
73
Среднее значение предсказанного количества школьников за год : 230200
RMSE : 1282.067873724638
74
Среднее значение предсказанного количества школьников за год : 123484
RMSE : 762.7238078224726
75
Среднее значение предсказанного количества школьников за год : 146098
RMSE : 376.16330233131606
76
Среднее значение предсказанного количества школьников за год : 148809
RMSE : 997.8066848009787
77
Среднее значение предсказанного количества школьников за год : 145364
RMSE : 1306.962491812737
78
Среднее значение предсказанного количества школьников за год : 36695
RMSE : 214.82690926138787
79
Среднее значение предсказанного количества школьников за год : 213665
RMSE : 1872.4920822120685
80
Среднее значение предсказанного количества школьников за год : 149220
RMSE : 376.2319933192686
81
Среднее значение предсказанного количества школьников за год : 99283
RMSE : 789.92176410434
82
Среднее значение предсказанного количества школьников за год : 16300
RMSE : 91.38616206143567
83
Среднее значение предсказанного количества школьников за год : 58749
RMSE : 2083.319787347906
84
Среднее значение предсказанного количества школьников за год : 20536
RMSE : 339.3524706016264
85
Среднее значение предсказанного количества школьников за год : 7322
RMSE : 18.924683901746672
    year   target0  target1  target2  target3  target4  target5  target6  \
0   2025  17874599   165511   130013   148546   257800   101728   126375
1   2026  17752359   164048   128376   145879   256177    98680   126819
2   2027  17527428   162176   126210   142626   252624    95016   126524
3   2028  17230680   159909   123908   138774   247244    91238   125603
4   2029  16851464   157537   121571   134637   241144    87346   123707
5   2030  16377468   154606   118801   129841   233174    83007   121402
6   2031  15809669   151338   115753   124403   223377    77895   118234
7   2032  15241722   148079   112855   119333   213751    72677   115006
8   2033  14659521   144829   110026   114181   203664    67714   111535
9   2034  14076030   141654   106874   108771   193135    62811   107538
10  2035  13552172   138713   104090   103768   183574    58463   103933
11  2036  13182316   136620   102077   100250   176633    55407   101419
12  2037  12883527   134875   100296    97145   170765    53129    99366
13  2038  12692074   133661    99073    95094   166827    51839    98338
14  2039  12562466   132836    98121    93712   163761    51092    97588
15  2040  12471939   132134    97406    92553   161387    50614    97212
16  2041  12463041   131979    97047    92093   160554    50496    97436
17  2042  12519182   132135    96909    92046   160911    50941    98240
18  2043  12654277   132704    97058    92515   162749    52014    99705
19  2044  12819931   133447    97301    93196   165246    53373   101458
20  2045  13005144   134318    97588    94009   168234    54948   103400

    target7  target8  ...  target76  target77  target78  target79  target80  \
0     74714   120779  ...    154213    144042     38349    216664    155456
1     73888   119876  ...    153738    142745     38421    215372    154764
2     72851   118522  ...    152574    141030     38383    213625    153792
3     71383   117133  ...    150833    139460     38276    211030    152157
4     69743   115367  ...    148713    137658     38114    207698    150033
5     67768   112878  ...    146279    135761     37733    203620    146986
6     65492   110155  ...    143372    133603     37241    198628    143234
7     63270   107509  ...    140442    131543     36694    193684    139464
8     61071   104802  ...    137346    129434     36164    188757    135551
9     58851   102087  ...    134535    127573     35617    183779    131548
10    56802    99614  ...    132328    126058     35160    179371    128176
11    55230    97961  ...    131103    125036     34852    176295    125658
12    54029    96570  ...    130310    124298     34668    173842    123478
13    53053    95723  ...    130110    123936     34597    172377    121955
14    52331    95100  ...    130025    123743     34591    171295    120967
15    51682    94688  ...    130448    123721     34659    170667    120045
16    51294    94670  ...    131203    123699     34820    170720    119674
17    51084    94931  ...    132379    123895     35087    171454    119704
18    51108    95549  ...    134029    124305     35469    172946    120222
19    51211    96313  ...    135794    124760     35900    174774    120930
20    51350    97176  ...    137601    125235     36356    176841    121757

    target81  target82  target83  target84  target85
0      99384     16174     63774     20544      6993
1      98979     16363     63637     20570      6980
2      98436     16641     63095     20607      7021
3      97902     16917     63002     20638      7054
4      97225     17244     62429     20676      7119
5      96407     17679     61731     20722      7207
6      95471     18168     60721     20773      7338
7      94567     18635     59564     20820      7472
8      93688     19079     58368     20866      7617
9      92848     19495     57097     20919      7769
10     92101     19843     55380     20964      7893
11     91558     20095     54386     20997      7974
12     91144     20269     53954     21026      8021
13     90902     20347     53597     21045      8024
14     90733     20407     53758     21061      8002
15     90649     20403     54016     21073      7973
16     90668     20367     54213     21078      7920
17     90774     20279     54758     21081      7852
18     90987     20142     55580     21078      7760
19     91241     19986     56498     21075      7672
20     91517     19820     57463     21072      7584

[21 rows x 87 columns]